name: Deploy via FTP

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual trigger

env:
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build the app
      run: npm run build
      
    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT || 21 }}
        local-dir: ./build/
        server-dir: ${{ secrets.FTP_SERVER_DIR || '/' }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env
          **/.env.*
          **/README.md
          **/DEPLOYMENT_SETUP.md
          **/.github/**
          **/src/**
          **/public/**
          **/package.json
          **/package-lock.json
          **/composer.json
          **/composer.lock
          **/vendor/**
          **/test-env.php
          **/env-template.txt
          **/compress-images.js
          **/vendor.zip 